Pydantic v2 support
MarcoMuellner/openapi-python-generator pull request #69
Opened 2024-03-28 07:35 UTC by 50Bytes-dev

2024-04-02 11:43 UTC, MarcoMuellner requested changes
Hey, thank you for the contribution! I like this! Can you make sure that the test workflow still runs and that the tests are adapted accordingly? 

I also think the python version doesn't necessarily need to be locked to 3.11.

2024-04-02 11:43 UTC, MarcoMuellner commented on pyproject.toml
> +python = ">=3.11,<3.12"
^3.9 should be fine here

2024-05-06 20:10 UTC, 305jthompson commented
Any update on this? I have a project that uses Pydantic v2 and I would love to use this in my project. Thanks!

2024-11-28 12:09 UTC, MarcoMuellner commented
Implemented by #76

2024-11-28 12:09 UTC, closed without merging